### ISSUE TITLE
文件"请求配对指令.txt"缺失

### ISSUE THREAD

**Issue by wangasd** [yuht/TC35661-Bluetooth#1]
问一下为什么没有这个文件"请求配对指令.txt" ,谢谢

**Comment by yuht** [comment]
首先说声对不起, 时间久远, 已经不记得当初怎么处理的这个事情了.  也可能是当初忘记了同步导致文件缺失.

最终的成品是使用keil+stm32(uart) 串口进行处理的. 参见说明中的另一个项目吧.
